"""Render the English feasibility documents from observed results and test records."""
import json,csv,hashlib,datetime
from pathlib import Path
from common import ROOT,OUT,DATA,save

def read(n):return json.loads((OUT/n).read_text())
def pct(x):return f'{x:.3f}%'
def table(headers,rows):
 def cell(x):return str(x).replace('|','/').replace('\n',' ')
 return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(cell(x) for x in r)+' |' for r in rows])+'\n'

def card(t):
 return '\n'.join([f"### {t['test_id']} — {t['purpose']}", '',f"- **Status:** {t['status']}.",f"- **Source and URL:** {t['source']}.",f"- **Procedure:** {t['procedure']}",f"- **Observed evidence:** {t['evidence']}",f"- **Limitations:** {t['limitations']}",f"- **Implication for CZ versus State:** {t['geography_implication']}",f"- **Next required action:** {t['next_action']}",'',''])

def write(n,s):(ROOT/'docs'/n).write_text(s.rstrip()+'\n')

if __name__=='__main__':
 h=read('hmda_snapshot_probe.json');g=read('geography_audit.json');o=read('occupation_audit.json');a=read('auxiliary_audit.json');q=read('qwi_sample_audit.json');e=read('compute_audit.json')
 tests=[]
 def add(id,status,purpose,source,procedure,evidence,limitations,implication,next_action):
  tests.append(dict(test_id=id,status=status,purpose=purpose,source=source,procedure=procedure,evidence=evidence,limitations=limitations,geography_implication=implication,next_action=next_action))
 hmda='[FFIEC/CFPB snapshot files](https://files.ffiec.cfpb.gov/static-data/snapshot/2025/2025_public_lar_csv.zip) and [field documentation](https://ffiec.cfpb.gov/documentation/publications/loan-level-datasets/lar-data-fields)'
 censusocc='[Census occupation concordances](https://www.census.gov/topics/employment/industry-occupation/guidance/code-lists.html)'
 dorn='[Dorn geography files](https://www.ddorn.net/data.htm)'
 add('R01','OPEN','Research-document and repository provenance','[Requested GitHub repository](https://github.com/ZhenghuiQu/genai-entry-jobs-mortgage)','Inspect local files, their provenance headers and Git state; attempt clone and authenticated connector read.','Eight unchanged independent Claude review files exist. Original assignment PDF, GPT package, full GPT–Claude cross-review and distinct Claude-only state audit are unavailable. Clone required authentication; connector returned 404.','Cannot assert these documents are absent from the remote repository; its tree and AGENTS.md are inaccessible.','Only the current request establishes CZ preference and State fallback; missing versions cannot be merged.','Provide a verified checkout/connection and all four missing document sets; integrate additive files without overwriting remote history.')
 add('A01','PASS','Official 2018–2025 snapshot access',hmda,'hmda_probe.py: HEAD, final 65,536 archive bytes, first 262,144 bytes; require HTTP 206 for ranges and reject full-object responses.','All eight HEADs returned 200 with Chrome-compatible TLS; ZIP directories and bounded CSV records were parsed for every year.','Standard urllib/curl returned 403. No full ZIP CRC or complete-file SHA256 was computed.','The same mortgage source supports either geography.','Use the demonstrated client, retain snapshot/ETag metadata, and verify full-file hashes only at authorized acquisition.')
 add('A02','PASS','Required-field schema and year differences',hmda,'hmda_analyze.py compares all headers and audits 15 required concepts as text.','All required concepts exist in all eight 99-column snapshot headers. Snapshot open_end_line_of_credit differs from Data Browser open-end_line_of_credit. The 2018 loan_to_value_ratio becomes combined_loan_to_value_ratio in 2019–2025.','The official public field page is not a literal snapshot header. Other naming differences between delivery routes are enumerated in hmda_schema_comparison.json.','Both geographies require explicit delivery-route and year adapters.','Freeze the observed adapters before writing the national parser; do not reuse the prior asserted CSV names.')
 add('A03','PASS','Observed codes and sentinel preservation',hmda,'Count raw string values, blank, NA, Exempt and 1111 before any filtering; preserve age/unit bins and identifiers.','2025 prefix has all eight age categories including 8888; reverse/open-end/business each have 392 code-1111 records out of 5,030. 2019 and 2021 prefixes contain county NA; CT extracts quantify county NA.','Prefix order is highly selective (2018 age 25–34 is 4,362/4,377); absence of a code in a sample is not absence nationally. Text Exempt is not observed in these three indicators.','Sentinel handling is identical across geographies; State can retain records with known state but unavailable county.','Keep separate missing/non-applicable/exempt flags; do not coerce 8888 or 1111 into ages/units or code 2.')
 add('A04','OPEN','National sample-funnel and representativeness',hmda,'Apply the existing provisional purchase filters to each downloaded sample and save stage counts.','hmda_filter_funnel.json records observed sample retention under actions 1–5, first lien, principal residence, site-built 1–4 units, and indicator no-or-exempt rules.','Only CT extracts are complete for their queried purchase-origination subset; national prefixes are not random and do not supply national application counts or rare-cell distributions.','Neither geography receives national acceptance counts from this test.','After parser/exposure approval, perform a count-only streaming census of the intended universe; keep all exclusions and reporting-threshold diagnostics.')
 add('B01','PASS','Original exposure classification and dv_rating_beta','[Eloundou source repository](https://github.com/openai/GPTs-are-GPTs) and [official O*NET-to-SOC crosswalk](https://www.onetcenter.org/taxonomy/2019/soc/2019_to_SOC_Crosswalk.xlsx?fmt=xlsx)','Pin the source Git commit; join complete occupation identifiers to official O*NET 2019 occupations and the SOC 2018 crosswalk.','923 unique ratings; all 923 match O*NET-SOC 2019 and the official SOC crosswalk. 798 scored detailed SOC groups; no missing beta; beta is bounded by 0 and 1. Only 762 codes also occur in the older 2010 list.','Code membership and exact official mappings establish usable taxonomy; ratings measure task capability, not adoption.','Occupation classification is a common dependency for both CZ and State.','Retain the pinned raw-source hash and exact concordance, not occupational prefix truncation.')
 pooled={r['age_group']:r for r in o['coverage'] if r['survey_year']=='pooled'}
 add('B02','FAIL','Employment-weighted coverage under a strict documented mapping',censusocc,'occupation_audit.py reads ACS worksheet identifiers and explicit Combines members, then joins complete official SOC codes. Numeric broad/minor groups and incomplete score groups stay unresolved.','Delaware 22–34 coverage is '+pct(pooled['22-34']['weighted_coverage_percent'])+' (88,016/123,656); 25–34 is '+pct(pooled['25-34']['weighted_coverage_percent'])+' (71,868/100,473). Neither satisfies the available review’s proposed 98% acceptance level. 107 unmatched young-worker groups are exported.','FAIL refers to this deliberately conservative mapping in DE, not proof that all lawful concordances or national exposure are impossible. Missing detailed membership and unrated All Other groups both contribute.','Moving to State does not fix occupational concordance; exposure must be repaired first.','Obtain explicit SOC hierarchy membership, resolve missing-rating policy and validate a complete national crosswalk; never fill by undocumented X/Y or prefix matches.')
 add('B03','PASS','2015–2019 PUMS coding and age-weight constructibility',censusocc+' and [ACS five-year ReadMe](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/ACS2015_2019_PUMS_README.pdf)','Read all 45,217 DE person records; infer survey year from SERIALNO; retain ESR 1/2, exact ages, PWGTP; compare OCCP/SOCP to official 2018 ACS worksheet.','All five years appear. In both requested young age bands, every observed SOCP agrees with the official 2018 PUMS group and has no blank code; 2015–2017 records already use that scheme in the pooled file.','This is empirical confirmation for DE only, not a nationwide harmonization certificate; exact age, residence and civilian employment are observed.','Age-weighted arithmetic can run at State or via PUMA allocation; complete-score coverage is still B02/B05.','Extend the survey-year consistency/missingness audit to the full approved baseline, retaining weights and unmatched codes.')
 add('B04','OPEN','Aggregated X/Y occupations and rating aggregation',censusocc,'Export official PUMS members, worksheet row numbers, candidate score ranges and component counts; use equal-child/equal-member means solely for the diagnostic.','X/Y groups are actual Census composites. Examples: 11-10XX combines 11-1011 and 11-1031, not 11-1021. Y groups contain explicitly listed subsets. Group 7640 lists 40-9095, which is not in the official SOC crosswalk; it was not silently corrected.','Equal means are technical assumptions, not employment shares. Some component groups are broad SOC codes requiring another explicit hierarchy step; some detailed occupations have no rating.','Both geographies share aggregation ambiguity; averaging occupations is separate from geographical employment weighting.','Freeze and justify within-group weights, missing-rating treatment and any documented erratum; rerun coverage before calculating a final exposure.')
 add('B05','OPEN','National employment-weighted exposure acceptance',censusocc,'Report coverage separately for 22–34/25–34 and all five sample years; attempt only national PUMS size/tail inspection, never its full records.','Pooled and year-specific DE coverage is archived; covered-weight allocation to two CZs conserves the included weights.','No national PUMS records were collected. Covered-only averages are diagnostics; no final state/CZ exposure is released.','The critical missing national exposure validation prevents choosing A or claiming State resolves the dependency.','Complete B02/B04, then obtain an approved national/count-by-occupation baseline and report both national and regional weighted coverage.')
 add('C01','PASS','County-to-1990-CZ key integrity',dorn,'Read the official Stata archive, ignore macOS resource-fork entries, preserve FIPS as zero-padded strings and test duplicates/missing.','3,141 county rows, 741 CZs, zero duplicate county keys and zero missing cells.','The crosswalk uses 1990 county definitions, not all modern equivalents.','CZ has a valid base join; State needs only stable state codes.','Apply audited vintage handling before joining mortgage records.')
 add('C02','PASS','2010 PUMA identifiers and allocation mass',dorn,'Read the included README; form int(ST)*100000+int(PUMA); test pair uniqueness, signs and PUMA weight sums at tolerance 1e-6.','4,077 pairs, 2,351 PUMAs, 741 CZs; 553 PUMAs split across CZs. No duplicate pairs/negative weights; maximum sum error is 7.31e-8. All 4,898 DE employed 22–34 records match, with zero allocation mass error.','Population-based afactor does not reveal a person’s true CZ; young-worker composition can vary within a PUMA. Float tolerances are technical assumptions.','CZ allocation arithmetic is technically valid; State avoids PUMA allocation uncertainty.','Retain fractional weights and expose uncertainty; do not randomly assign one CZ or normalize away missing joins.')
 add('C03','PASS','Historical county changes in a baseline inventory',dorn+' and [2019 county population file](https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.csv)','Audit all 2019 county IDs against Dorn; separately evaluate documented 12086→12025, 46102→46113 and Broomfield→28900 candidates.','For the provisional contiguous+DC, CT-excluded inventory: 3,097/3,100 IDs and 99.131% population match raw; documented candidates yield 3,100/3,100 and 100% population coverage.','This is a population inventory, not HMDA coverage. Broomfield includes a small contribution from a county in another CZ; Dorn’s assignment is an approximation needing explicit design acceptance.','Historic changes appear manageable for CZ; State sidesteps them.','Approve genuine rename links separately from Broomfield’s approximation; report shares affected and retain unmatched logs.')
 add('C04','FAIL','Connecticut planning-region compatibility',dorn+' and [Census final CT change](https://www2.census.gov/geo/pdfs/reference/ct_county_equiv_change.pdf)','Compare 2018/2023/2024/2025 CT purchase-originations with the unchanged 1990 county lookup.','Old CT counties appear through 2023. Nine 09110–09190 planning-region codes appear in 2024/2025; zero of 35,150/35,676 rows match old Dorn geography. County NA counts are 359/336.','No tract-level reconstruction was attempted. Two 2018 CT-filtered rows have out-of-state county prefixes; one 2019 national-prefix row is also inconsistent.','Unharmonized CT fails CZ. State codes avoid the planning-region break, subject to an explicit consistent CT policy.','Choose a documented tract/town bridge or a consistent all-year CT exclusion; never assign planning regions arbitrarily to old counties/CZs.')
 add('C05','OPEN','Coverage of the complete intended HMDA sample',hmda+'; '+dorn,'Tabulate every unmatched sample identifier before filtering; report provisional-purchase coverage separately; check county/state agreement.','All eight prefix coverage rates and all CT-extract unmatched counts are in geography_audit.json and the geography audit document. Known missing, changed and inconsistent codes remain visible.','No complete intended national loan universe was retrieved. Prefix coverage is not a national percentage; candidate mappings have not been adopted.','CZ acceptance remains conditional; State also needs sample-policy reconciliation.','Run a count-only national geography audit after acquisition approval; report missing county, missing state, mismatch and patch/exclusion shares separately.')
 add('D01','PASS','QWI age coverage and Michigan limitation','[LEHD QWI releases](https://lehd.ces.census.gov/data/qwi/latest_release/)','Fetch version_qwi.txt for all 50 states+DC, parse the unadjusted QWI_F interval, and retain all release strings.','All 51 retrieved manifests identify R2026Q3/V4.14.0. 49 end at 2025Q4; Michigan ends 2021Q4 and Alaska 2016Q2. A03=22–24, A04=25–34, A05=35–44, A06=45–54.','Publication endpoint is not proof of nonmissing county cells; adjusted/seasonal variants end one quarter earlier and are not the tested unadjusted series.','MI’s post-period mechanism data are unavailable at either geography; cross-border CZ membership needs handling.','Pre-specify a harmonized mechanism sample; do not treat unreleased MI values as zero or carry them forward.')
 add('D02','PASS','Observed QWI employment/hiring missingness','[DE QWI county-sector file](https://lehd.ces.census.gov/data/qwi/latest_release/de/qwi_de_sa_f_gc_ns_op_u.csv.gz) and [status labels](https://lehd.ces.census.gov/data/schema/latest/label_flags.csv)','Select geo_level C, ind_level A, sex 0, industry 00, A03–A06, 2016Q1–2025Q4; compare against a complete 3×4×40 grid.','480 expected and observed county-age-quarter cells; no duplicates, missing Emp/HirA or absent cells; every sEmp/sHirA is 1.','Only DE totals were examined. The file also contains state aggregates, which must be excluded; national/small-industry suppression is unresolved. QWI jobs are workplace-based, not persons/resident occupations.','Small-state mechanism-source arithmetic is available; State does not remove national missingness.','Audit missingness nationally by geography/age/quarter with flags -2,-1,5,11 distinct from distorted-but-released 7,9,12.')
 add('D03','PASS','ACS baseline affordability and no-key alternative','[ACS sequence documentation](https://www.census.gov/programs-surveys/acs/data/summary-file/sequence-based/2019.html) and [2019 variable metadata](https://api.census.gov/data/2019/acs/acs5/variables.json)','Reject HTML from the no-key API; read official sequence lookup and four DE bulk files, join LOGRECNO to summary-level 050/component 00.','All three counties have positive B25077 home-value and B19013 household-income medians, B25003 owner units and B01003 population. Ratios are 3.622, 3.529 and 4.094. Metadata/sequence positions agree.','The API body says Missing Key despite HTTP 200. National county missingness and aggregating county medians into a CZ affordability index remain unresolved.','Bulk collection can support CZ or State without pretending no-key API access works.','Use the demonstrated bulk path or a user-supplied environment key; settle aggregation weights and ratio/log order before implementation.')
 add('D04','PASS','2019 population weights and region/division coding','[Census 2019 population file](https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.csv) and [layout](https://www2.census.gov/programs-surveys/popest/datasets/2010-2019/counties/totals/co-est2019-alldata.pdf)','Keep SUMLEV 050 and validate STATE+COUNTY and POPESTIMATE2019; inspect REGION/DIVISION codes.','3,142 counties, no duplicate county keys or blank population weight; July 1, 2019 weights and four regions/nine divisions are explicitly coded.','These weights differ from pooled ACS 2015–2019 population; changing the intended weight is a methodological choice, not an automatic substitution.','Either geography can receive documented 2019 weights once vintage/sample policy is fixed.','Freeze population-weight vintage and relevant aggregation universe; retain C03 change accounting.')
 add('D05','OPEN','Required regional characteristics and price-control inputs','[PUMS dictionary](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2015-2019.txt), [telework source](https://github.com/jdingel/DingelNeiman-workathome), [FHFA file route](https://www.fhfa.gov/hpi/download/annual/hpi_at_county.csv)','Inspect SCHL/NAICSP/SOCP/PWGTP in young DE records; detect FHFA format by signature rather than extension; inspect telework identifiers.','SCHL and NAICSP have no blanks among 4,898 young employed DE persons. Telework has 968 occupational rows. FHFA request returns an XLSX workbook with 106,252 rows, not CSV; it includes missing HPI and multiple index bases.','Exact tech-industry membership, telework taxonomy mapping, national FHA baseline shares and national control missingness are not certified.','State avoids geographical allocation but shares occupation/industry coding concerns.','Create explicit Census industry and 2010→2019 telework concordances; choose FHFA series/base and quantify control availability before using them.')
 add('E01','PASS','Observed download and disk budget',hmda,'Read all eight ZIP central directories, including ZIP64 sizes, and measure current disk/RAM.','HMDA ZIP total is 7,685,735,098 bytes; expanded CSV total 53,046,718,437 bytes; largest CSV 10,206,391,218 bytes. Machine has 8 logical CPUs, 16 GiB physical RAM and about 65.4 GB free during the test.','Complete PUMS/QWI/conversion/spill space is not included in the mortgage sum; available disk changes over time.','Streaming/year-at-a-time aggregation is applicable to both geographies; State has fewer grouping cells.','Reserve headroom and process one year at a time; do not retain all expanded CSVs beside ZIPs/Parquet on this disk.')
 add('E02','PASS','Bounded DuckDB streaming aggregation correctness',hmda,'compute_probe.py: 256 MB engine limit, two threads; group county×age×action; compare every count with an independent Python csv.Counter; repeat on gzip.','All three samples pass exact count equality: 4,377 early rows, 5,030 late rows and 35,676 CT late rows. The largest plain/gzip scans take '+f"{e['tests'][-1]['duckdb_seconds']:.3f}/{e['tests'][-1]['gzip_duckdb_seconds']:.3f}"+' seconds in the recorded run; peak process RSS is '+f"{e['machine']['peak_rss_bytes']/1e6:.1f}"+' MB.','Tiny/warm-cache samples are not national throughput measurements; ZIP is not read directly by DuckDB, and engine memory limits do not cap whole-process RSS.','Both aggregation geographies have a demonstrated parser/arithmetic path.','Spool one validated CSV or feed a tested bounded decompression stream; measure a larger approved count-only pilot before a national timing commitment.')
 add('E03','OPEN','National resource and deadline guarantee',hmda,'Separate exact archive sizes/measured samples from hypothetical production budgets.','All-years ZIP+CSV retention would use 60.73 GB before auxiliary files/output/spill. The tested machine’s free space leaves little room for that layout.','No complete national scan, CZ hash-join, Parquet size, spill peak, network-throughput or implementation deadline was measured; no full regression performance test is allowed in this stage.','Neither A nor B follows from the microbenchmark; missing exposure/document dependencies independently require C.','After the critical concordance is resolved, approve a sequential storage plan and bounded representative pilot; record a concrete deadline before any deadline-based fallback.')
 save('test_register.json',tests)
 meta='Date: 2026-10-09 (Asia/Shanghai). Scope: Day 1–2 feasibility only. Retrieval timestamps are UTC in the source manifest.\n\n'
 legend='**Evidence labels.** VERIFIED DATA FACT = directly downloaded/parsed or official metadata; TECHNICAL ASSUMPTION = diagnostic implementation rule; UNRESOLVED CHOICE = design/mapping policy not fixed; RECOMMENDATION = action supported by those facts. PASS is limited to the stated procedure and denominator; FAIL rejects the tested configuration; OPEN has an unresolved dependency.\n\n'
 main='# Day 1–2 Feasibility Gate Report\n\n'+meta+'## Recommendation\n\n**C. A critical data dependency remains unresolved and needs further work.** CZ remains the provisional preferred geography and State the pre-specified feasibility fallback. No treatment coefficient or treatment-effect significance was estimated or inspected. No geography was chosen using outcome regressions.\n\n'+legend
 main+='HMDA access, eight-year schemas, Dorn key integrity, small-state auxiliary access and streaming arithmetic are verified. The strict official-membership occupational mapping covers only 71.178%/71.530% of DE employed residents aged 22–34/25–34, and national weighted coverage is not observed. Numeric SOC hierarchy, unrated occupations, group weights and one published invalid member remain unresolved. Four required research-document sets and the existing repository history are inaccessible. State aggregation cannot repair these exposure/provenance dependencies, so a definitive fallback recommendation would be premature.\n\n'
 main+='## Gate summary\n\n'+table(['Gate','Outcome','Interpretation'],[['A — HMDA','PASS access/schema; OPEN national funnel','All eight capped snapshot samples obtained; names differ across route/year.'],['B — Occupations','FAIL tested coverage; OPEN completed concordance','No prefix fill, final exposure or nationwide coverage claim.'],['C — Geography','PASS base crosswalk; FAIL unbridged CT; OPEN universe','2019 inventory candidates are not mortgage-coverage evidence.'],['D — Auxiliary','PASS tested sources; OPEN national cells/controls','MI post-2021 missing; official ACS bulk alternative works.'],['E — Compute','PASS bounded correctness; OPEN production budget','Exact sizes observed, national runtime/memory not extrapolated.'],['Research provenance','OPEN','Eight local Claude files only; distinct cross-reviews are not merged.']])+'\n'
 main+='## Year-specific HMDA evidence\n\n'+table(['Year','Prefix rows','ZIP bytes','CSV bytes','Required concepts'],[[y,h[y]['sample']['rows'],e['hmda_archive_sizes'][y]['zip_bytes'],e['hmda_archive_sizes'][y]['csv_bytes'],'15/15'] for y in map(str,range(2018,2026))])+'\nEach sample is the complete CSV lines decompressed from a fixed 256 KiB archive prefix. The truncated last line is discarded. These are deterministic, nonrandom schema probes. Raw range hashes are not full-archive hashes. 2018 has `loan_to_value_ratio`; 2019–2025 have `combined_loan_to_value_ratio`. Other snapshot field names/order are stable after that change; all eight snapshots have 99 columns. Data Browser has a different naming convention, including hyphens in `open-end_line_of_credit`, co-applicant fields and repeated race/ethnicity/AUS/denial-reason fields.\n\n'
 main+='## Early and late observed codes and types\n\n'
 codes=[]
 for f in h['2018']['sample']['fields']:
  early=h['2018']['sample']['fields'][f];late=h['2025']['sample']['fields'][f]
  def short(v):return ', '.join(v['codes']) if v['codes'] is not None and v['n_unique']<=40 else f"{v['n_unique']} distinct identifiers; see full code-count JSON"
  typ='string identifier' if f in ['lei','county_code','state_code'] else 'string bin' if f in ['applicant_age','total_units'] else 'coded integer stored as CSV text'
  codes.append([f,typ,short(early),short(late)])
 main+=table(['Required concept','Safe analytic type','2018 observed','2025 observed'],codes)+'\nDetailed counts for all eight years and CT extracts are in `results/feasibility/hmda_field_codes.json`. `8888` is non-applicable applicant age; preserve it as a separate category/exclusion flag. `1111` denotes partial exemption in the three product indicators. `NA` county and blank values remain distinct from Exempt/non-applicable values. Retaining exempt product indicators follows the available review only provisionally: exemption does not prove the product is code 2. Numeric parsing is applied only after sentinel separation. `total_units` must retain its multiunit ranges, never integer-cast blindly.\n\n'
 main+='## Tests and acceptance boundary\n\n'+''.join(card(t) for t in tests if t['test_id'][0] not in ['B','C'])
 main+='## Detailed occupation and geography gates\n\nTests B01–B05 are recorded in [occupation_crosswalk_audit.md](occupation_crosswalk_audit.md); C01–C05 in [geography_audit.md](geography_audit.md). Every test is also available as a structured record in `results/feasibility/test_register.json`. Sources, versions, hashes and failures are indexed in [data_source_registry.md](data_source_registry.md). Unresolved design choices are in [design_decisions_pending.md](design_decisions_pending.md).\n\n'
 pums = read('pums_resource_audit.json')
 main+='## Computational recommendation\n\nExact HMDA totals imply 7.686 GB compressed and 53.047 GB expanded (decimal GB). Retaining both consumes 60.732 GB, versus the free disk recorded in `compute_audit.json` (about 65.4 GB), leaving only about 4.7 GB before PUMS, QWI, output or spill. The largest one-year CSV is 10.206 GB. Recommend a single-year ZIP/CSV spool followed by column-pruned aggregation and deletion under a documented retention policy; do not start that download now. A hypothetical 7.686 GB ZIP archive plus one largest CSV is 17.892 GB, before auxiliary/output/spill; this is arithmetic, not a measured production peak. '
 if pums.get('zip_entries'):
  main+=f"National PUMS metadata-only HEAD/ZIP-tail reads establish {int(pums['head']['headers']['content-length'])/1e9:.3f} GB compressed and {sum(x['uncompressed_bytes'] for x in pums['zip_entries'] if x['name'].endswith('.csv'))/1e9:.3f} GB expanded person CSVs. No national PUMS records were downloaded. "
 main+='QWI CA/DE/MI HEAD sizes are in `qwi_download_sizes.json`. Small samples do not justify a national runtime estimate or application-level regression RAM claim.\n\n'
 main+='## Reproduction and stopping rule\n\nSee the root README and Makefile. `make feasibility-analyze` rebuilds local audits/reports from the capped ignored downloads; `make feasibility` also repeats bounded acquisition. The append-only manifest records unsuccessful attempts as well as successful bodies. Raw data and the local virtual environment are Git-ignored. Original review files and this request are preserved with hashes. Repository-access limitations are recorded in `audit/repository_access.md`; the available AI audit summary is explicitly not a complete native transcript export.\n\nStop at this evidence report. The next instruction may resolve exposure/geography/document dependencies; national regressions, robustness and paper drafting require a subsequent implementation instruction.\n'
 write('feasibility_gate_report.md',main)
 geo='# Geography Audit\n\n'+meta+legend+'## Scope and official inputs\n\nThe official files are `cw_cty_czone.zip`, `cw_puma2010_czone.zip`, `cw_czone_state.zip` and Dorn’s county-code-change PDF, last updated September 2021. [Dorn’s page](https://www.ddorn.net/data.htm) explicitly distinguishes 1990 county definitions and the 2010 PUMA mapping used for 2012–2021 ACS. The state crosswalk assigns a dominant state, which must not be confused with restricting a cross-border CZ to that state.\n\n'+''.join(card(t) for t in tests if t['test_id'].startswith('C'))
 geo+='## Observed HMDA sample coverage before any geographic drops\n\n'+table(['Sample','Rows','Matched to raw Dorn','Raw coverage','Unmatched counts'],[[n,v['rows'],v['matched_rows'],pct(v['row_coverage_percent']),json.dumps(v['unmatched'],sort_keys=True)] for n,v in g['hmda_samples'].items()])+'\nThese denominators include missing county codes, every action/product in a national prefix, and only purchase originations in the CT API extracts. They are not the national intended analysis sample. `geography_audit.json` also reports the provisional purchase-filter subset and separate candidate-map coverage. No unmatched loan was removed from the raw data.\n\n'
 geo+='## Historical changes and allocation errors\n\n'+table(['Code','Official documented treatment','Status'],[['12086','Rename to predecessor 12025; CZ 7000','Verified link, candidate application'],['46102','Rename to predecessor 46113; CZ 27704','Verified link, candidate application'],['08014','Dorn recommends CZ 28900; originated from multiple counties','Approximation requires explicit acceptance'],['09110–09190','Nine new CT planning regions, no old-county Dorn key','Unresolved, no arbitrary match'],['NA/blank county','No geographic assignment','Retain missingness counts'],['County/state disagreement','1 row in 2019 prefix; 2 in 2018 CT extract','Retain/flag; reconciliation OPEN']])+'\nIn the 2019 inventory after excluding AK/HI/CT, raw matched population is 319,725,237 of 322,526,819 (99.131%). The three documented candidate treatments cover the entire inventory. This does not authorize treating Broomfield’s approximation as an exact historical boundary bridge. No Alaska vintage repair is attempted under that provisional universe.\n\nThe PUMA key is the seven-character combined identifier (two-digit state FIPS plus five-digit PUMA) represented numerically as `100000*ST+PUMA`; leading-zero strings should be retained for audit display. Weight sums lie between 0.999999936670 and 1.000000073065. At tolerance 1e-6, 100% of 2,351 PUMAs pass mass conservation. All 553 split PUMAs remain fractional; no random assignment, nearest-neighbor match or arbitrary renormalization is used.\n\n## CZ versus State implication\n\nVERIFIED DATA FACT: the base Dorn join and allocation factors are sound. UNRESOLVED CHOICE: accept the published Broomfield approximation, exclude CT consistently, or construct an official fine-geography bridge. TECHNICAL ASSUMPTION: population allocation represents young employment inside each PUMA. RECOMMENDATION: retain CZ provisionally and keep State available; complete C05 and occupational gates before selecting either. The existing review’s suggested county predecessor patch is not applied generically to arbitrary splits.\n'
 write('geography_audit.md',geo)
 occ='# Occupation Crosswalk Audit\n\n'+meta+legend+'## Source chain and mapping rule\n\nOriginal ratings are pinned to Git commit `'+json.loads((DATA/'exposure_commit.json').read_text())['sha']+'` in the Eloundou author repository. Join `O*NET-SOC Code` to the official O*NET-SOC 2019→SOC 2018 workbook using the full code. Then use the ACS worksheet of the official 2018 ACS/SIPP PUMS occupation list. The SIPP worksheet is not substituted. The pooled ACS five-year dictionary and [ReadMe, page 18](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/ACS2015_2019_PUMS_README.pdf) identify X/Y as aggregates.\n\nNo wildcard or prefix code inference is performed. Explicit Census `Combines` rows determine component membership. A group is scored only when every explicitly enumerated member is a scored exact detailed SOC. Numeric broad/minor codes are retained as unresolved rather than assumed to be detailed codes. A source-defined membership map and a scoring-weight assumption are separate objects.\n\n'+''.join(card(t) for t in tests if t['test_id'].startswith('B'))
 occ+='## Employment-weighted sample coverage\n\n'+table(['Ages','Survey year','Persons','PWGTP denominator','Scored weight','Coverage','Missing/inconsistent code weight'],[[r['age_group'],r['survey_year'],r['rows'],r['weight'],r['covered_weight'],pct(r['weighted_coverage_percent']),f"{r['missing_socp_weight']}/{r['official_code_inconsistent_weight']}"] for r in o['coverage']])+'\nDenominator: all civilian employed residents (ESR 1/2) in the exact requested age band, including unmatched occupational groups. It is not the matched subsample denominator. PWGTP values are five-year weights; their pooled sum is not multiplied by five. No employed unmatched group is silently dropped when computing coverage.\n\n'
 occ+='## Ambiguity, exclusions and diagnostic construction\n\nFor ages 22–34, 12,406/123,656 employment weight lies in X/Y codes. At least 25,621/123,656 weight lies in explicit multi-member or multi-O*NET-child groups under this conservative diagnostic; unresolved broad groups can add further ambiguity. All 107 unmatched young-worker OCCP/SOCP groups and their weights are exported in `occupation_unmatched_groups.csv`. Group labels, explicit members, Excel row numbers, score range and status for all 529 PUMS groups are in `occupation_mapping_diagnostic.csv`; observed ambiguous groups are in `occupation_ambiguous_groups.csv`.\n\nExamples requiring explicit hierarchy expansion include `25-1000` postsecondary teachers, `25-2020` elementary/middle-school teachers, `15-1230` computer support, and `53-3030` driver/sales workers and truck drivers. A nonzero terminal “All Other” code is never filled from neighboring occupations. The group-7640 component `40-9095` is retained as an invalid official-source member until an authoritative correction is established.\n\nTECHNICAL ASSUMPTION: an equal mean over scored O*NET children within a SOC, then an equal mean over explicitly enumerated detailed SOC members within a PUMS group. This is deliberately transparent and provisional. The official crosswalk supplies memberships, not these weights. Employment weights PWGTP, and PWGTP×afactor for CZ allocation, are applied only after occupation scores are defined. Covered-only arithmetic conserves included weights in two DE CZs but does not constitute a complete exposure. No index is standardized or released for treatment estimation.\n\n## Unresolved boundary\n\nA complete occupation mapping could materially raise these conservative coverage rates; 71% is not an estimate of the maximum achievable coverage. A national pass or final index requires official detailed membership for broad SOC groups, a defensible policy for unrated components, resolved source errors, age-specific employment-weighted coverage by region and survey year, and frozen aggregation weights. State aggregation alone does not meet these requirements.\n'
 write('occupation_crosswalk_audit.md',occ)
 pending='# Design Decisions Pending\n\n'+meta+legend+'## Research versions must remain separate\n\n'+table(['Document set','Observed availability','Geography/authority'],[['Original research assignment PDF','Missing locally; cited filename 研究任务说明.pdf in Claude review','Contents not independently inspected'],['Independent GPT literature-review package','Missing locally; remote inaccessible','No inferred specification'],['Independent Claude literature-review package','Eight original files in literature/','Proposes CZ; industry-based exposure fallback'],['Complete GPT–Claude cross-review','Missing locally; user describes it','CZ provisionally preferred per current request'],['Distinct Claude-only cross-review/audit','Missing locally; user describes it','State alternative per current request; do not equate with Claude literature package']])+'\nThe inaccessible remote cannot be searched for missing documents. “Missing locally” is not a claim about its repository contents. The current user instruction controls: CZ is provisional and State is the pre-specified feasibility fallback; neither review can silently finalize the geography. R01 records the provenance test.\n\n'
 pending+='## Preserved provisional specification from the available package\n\n- Mortgage panel window 2018–2025; young applicants 25–34 versus 35–44; auxiliary `<25` and placebo 45–54 contrasts. HMDA `<25` cannot identify ages 22–24 exactly.\n- Occupational exposure baseline ACS 2015–2019, civilian employed residents aged 22–34; separately check 25–34. Keep both definitions visible.\n- Treatment timing remains pre-2023 versus 2023–2025, with 2022 reference; no outcome-driven retiming.\n- Mortgage purchase applications: actions 1–5, first lien, principal residence, site-built 1–4 units, closed-end/nonreverse/nonbusiness restrictions. The available review retains partial-exempt product indicators provisionally.\n- QWI age groups A03/A04/A05/A06, unadjusted private workplace jobs; reference-quarter conventions and suppression policies are retained as proposals, not evaluated labor effects.\n- Denial/pricing remain selection-sensitive secondary outcomes; no primary coefficient or significance inspection occurred. Estimator, fixed effects, inference and normalization are not reoptimized in this feasibility audit.\n\n'
 pending+='## Inconsistencies and unresolved choices\n\n'+table(['ID','Observed tension or pending decision','Evidence / next action'],[['P01 — Review provenance','User describes a Claude-only state audit; local Claude literature package itself proposes CZ','Obtain the distinct audit and both other versions; do not infer a contradiction from missing text'],['P02 — Fallback meaning','Local DEC-D02 is industry-exposure/share-form fallback; current instruction specifies State feasibility fallback','Keep these as two distinct choices; State does not license changing occupation exposure'],['P03 — Physical schema','Review asserts Data Browser-style columns for snapshots and loan_to_value_ratio in 2025','Observed underscore snapshot fields and 2019 CLTV rename require parser adapters'],['P04 — Occupational membership','Review proposes simple 8→6 truncation and X means','Official exact concordances/explicit composites required; B02 fails conservative sample coverage'],['P05 — Geographic commitment','Local DEC-G01/DEC-G02 mark CZ/CT exclusions decided','Current instruction makes geography provisional; CT bridge/exclusion and Broomfield approximation need reconciliation'],['P06 — QWI sample size','Local plan says 47 states+DC after excluding CT/MI from contiguous states','48 contiguous minus CT/MI = 46 states+DC = 47 jurisdictions; fix implementation acceptance counts'],['P07 — No-key API','Local REQ-REPRO-04 asserts no key is needed','Observed 200 HTML Missing Key; DE bulk-summary route succeeds'],['P08 — Storage','Local HMDA expanded estimate around 40–50 GB and 6–8 GB zipped','Observed 53.047 GB CSV +7.686 GB ZIP; available disk cannot safely retain all plus auxiliary/output'],['P09 — Rate/value controls','Local affordability index allows owner-unit or population weighting; FHFA assumed CSV','Freeze weight/order of logs and ratios; actual FHFA response XLSX, with missing/base-vintage issues'],['P10 — Cross-border CZs','MI missingness and CT exclusion can leave partial CZs; dominant state is only a clustering label','Define complete-versus-partial CZ handling and calculate affected county/employment shares'],['P11 — Exposure aggregation','Equal O*NET/SOC member means are not employment-weighted internal group scores','Freeze component weights/missing-rating policy before final baseline; do not select by mortgage effects'],['P12 — Geographic mismatches','Three sample rows show county/state inconsistency','Flag and investigate; preserve counts rather than assign from one field silently'],['P13 — Deadline','No current implementation deadline appears in the request; local plan uses one week','A deadline-based recommendation B needs a specified deadline and measured remaining burden'],['P14 — Audit trail integration','Native app history available, complete transcript export unavailable; existing remote logs inaccessible','Preserve originals, request/native-export complete history, integrate additive files without replacing remote tree']])+'\n'
 pending+='## Facts, assumptions and recommendation\n\nVERIFIED DATA FACTS: eight snapshot files are accessible through the demonstrated client; required concepts exist; CT planning-region codes fail unchanged county mapping; Michigan has no post-2021 QWI; DE occupation coverage under the strict exact-member mapping is below the proposed threshold. TECHNICAL ASSUMPTIONS: equal score means, float tolerance 1e-6, sequential disk layout and diagnostic filters. UNRESOLVED METHODOLOGICAL CHOICES: full SOC memberships/unrated scores, CT/MI/cross-border policy, exposure ages/weights, controls and authentic cross-review specifications. RECOMMENDATION: C, complete those dependencies; retain CZ provisional and State fallback. Do not use regression results to resolve any item.\n\n## Next authorized feasibility actions\n\n1. Restore document/repository access and compare the actual two cross-reviews line-by-line.\n2. Complete the explicit occupational hierarchy and missing-score policy, then evaluate weighted coverage nationally for both age bands without inspecting mortgage effects.\n3. Resolve CT/Broomfield/cross-border rules and audit the full intended geography using counts only after acquisition procedure approval.\n4. Quantify nationwide QWI/control missingness, update a sequential storage budget and bounded pilot, and state the deadline.\n5. Decide A/B/C on those facts, freeze design decisions, and obtain a subsequent implementation instruction before national regressions.\n'
 write('design_decisions_pending.md',pending)
 manifest=[json.loads(x) for x in (OUT/'source_manifest.jsonl').read_text().splitlines()]
 registry='# Data Source Registry\n\n'+meta+legend+'## Retrieval manifest and version policy\n\nThe authoritative append-only machine manifest is `results/feasibility/source_manifest.jsonl`. Every attempted acquisition records URL/final redirect, UTC timestamp, method, requested range, HTTP backend/status, version label, response headers, bytes, SHA256 when a body was actually retrieved, and error if any. HEAD requests hash no body; national range hashes cover only those bytes. Successful small complete archives have full downloaded-object hashes. Downloaded microdata, workbooks, source pages, credentials and virtual environments are excluded from Git. Derived aggregate audit results are committed.\n\nThe Eloundou source is pinned by Git SHA; the ACS baseline is the official 2015–2019 five-year release; population weights are Vintage 2019, July 1; QWI manifest labels identify V4.14.0/R2026Q3 and per-state build identifiers. Mutable `latest_release` files are identified by the retrieval/hash, not assumed timeless. Raw FHFA URL redirects/content signature are audited separately. For unpinned author-source controls, their content hash is the retrieved version; pinning an upstream commit remains required before implementation.\n\n'
 registry+='## Test-linked source decisions\n\n'+''.join(card(t) for t in tests if t['test_id'] in ['A01','B01','C01','D01','D03','D04','D05','E01'])
 # Latest successful observed bodies, plus failures with no success, are displayed.
 last={}
 for r in manifest:last[r['id']]=r
 registry+='## Individual source objects and attempts\n\n'+table(['ID','Version','UTC retrieval','HTTP / bytes','SHA256 or scope','Source URL'],[[r['id'],r['version'],r['retrieved_at_utc'],f"{r.get('status','NONE')} / {r.get('bytes','—')}",r.get('sha256') or r.get('error') or 'HEAD metadata only',f"[source]({r['url']})"] for r in last.values()])+'\nThe table shows the last attempt per logical object; earlier 403/SSL/404 attempts remain in the append-only manifest. For repeated retrieval the last attempt can fail even when an earlier valid file exists; offline validation uses the matching successful hash. The guessed ACS filename/PUMS code-list URL and the BLS workbook route returned 404/403; only the subsequently observed official successful sources are used. API HTTP 200 is insufficient: `acs_counties.json` is HTML Missing Key, explicitly excluded from data-value use.\n\n'
 registry+='## Unavailable research sources\n\nOriginal assignment, GPT review, full GPT–Claude cross-review and the distinct Claude-only state audit have no retrieved bytes or content hashes. They are not fabricated manifest entries. The local Claude package has an independent file-hash manifest; repository access evidence and the preserved request live under `audit/`. Web-tool verification of the HMDA public field documentation and BLS SOC hierarchy establishes source context, but does not supply a locally hashed original document or complete machine-readable hierarchy. BLS hierarchy remains unused for filling occupational matches.\n\n## Derived artifacts\n\n`local_artifact_manifest.json` hashes ignored derived CSV prefixes and local audit outputs separately from source downloads. `research_document_manifest.json` hashes every preserved local review. The audit validator confirms every available downloaded body against a successful acquisition hash. Full raw source responses are intentionally not committed.\n'
 write('data_source_registry.md',registry)
 print('Rendered five English documents and',len(tests),'structured tests')
